---
title: "Gov 51 Final Project Code / Notes"
output:
  pdf_document: default
  html_document: default
---
```{r}
## reading data
survey <- read.csv("https://raw.githubusercontent.com/themarshallproject/incarcerated_survey/master/data/incarcerated_survey_responses-marshallproject_slate-march_2019.csv")

## removing any NA values from the data
survey_no_NA <- na.omit(survey)
```

## Race

```{r}
## creating race variable for data frame with NA (race_prisoner)
survey$race_prisoner <- "Other/Unknown"
survey$race_prisoner[survey$identifies_as_hispanic_or_latinx == "TRUE"] <- "Hispanic"
survey$race_prisoner[survey$identifies_as_black == "TRUE"] <- "Black"
survey$race_prisoner[survey$identifies_as_white == "TRUE"] <- "White"

race_prisoner_and_facility_length_table <- table(survey$race_prisoner, survey$length_in_this_facility)
knitr::kable(race_prisoner_and_facility_length_table, digits = 4, caption = "Prisoner Race Based on Jail Time")

race_prisoner_and_facility_length_prop_table <- prop.table(table(survey$race_prisoner, survey$length_in_this_facility)) 


## creating race variable for data frame with no NA (race_prisoner)
survey_no_NA$race_prisoner <- "Other/Unkown"
survey_no_NA$race_prisoner[survey_no_NA$identifies_as_hispanic_or_latinx == "TRUE"] <- "Hispanic"
survey_no_NA$race_prisoner[survey_no_NA$identifies_as_black == "TRUE"] <- "Black"
survey_no_NA$race_prisoner[survey_no_NA$identifies_as_white == "TRUE"] <- "White"

race_prisoner_and_facility_length_table_no_NA <- table(survey_no_NA$race_prisoner, survey_no_NA$length_in_this_facility)
knitr::kable(race_prisoner_and_facility_length_table_no_NA, digits = 4, caption = "Prisoner Race Based on Jail Time (no NA)")

race_prisoner_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$race_prisoner, survey_no_NA$length_in_this_facility))

```


## Political Party

```{r}
## creating variables in the data frame with NA (party --> political_party)

survey$political_party[survey$party == "The Republican party"] <- "Conservative"
survey$political_party[survey$party == "The Democratic party"] <- "Liberal"
survey$political_party[survey$party == "Independent"] <- "Indep"
survey$political_party[survey$party == "Other"] <- "Other"

political_party_and_facility_length_table <- table(survey$political_party, survey$length_in_this_facility)
knitr::kable(political_party_and_facility_length_table, digits = 4, caption = "Political Party of Prisoners Based on Jail Time")

political_party_and_facility_length_prop_table <- prop.table(table(survey$political_party, survey$length_in_this_facility))


## creating variables in the data frame with no NA (party --> political_party)
survey_no_NA$political_party[survey_no_NA$party == "The Republican party"] <- "Conservative"
survey_no_NA$political_party[survey_no_NA$party == "The Democratic party"] <- "Liberal"
survey_no_NA$political_party[survey_no_NA$party == "Independent"] <- "Indep"
survey_no_NA$political_party[survey_no_NA$party == "Other"] <- "Other"

political_party_and_facility_length_table_no_NA <- table(survey_no_NA$political_party, survey_no_NA$length_in_this_facility)
knitr::kable(political_party_and_facility_length_table_no_NA, digits = 4, caption = "Political Party of Prisoners Based on Jail Time (no NA)")

political_party_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$political_party, survey_no_NA$length_in_this_facility))
```

## Length in Facility

```{r}
## creating variable for length in facility with NA (length_in_this_facility --> facility_length)

survey$facility_length <- 0
survey$facility_length[survey$length_in_this_facility == "10 years or less"] <- -1
survey$facility_length[survey$length_in_this_facility == "Over 10 years"] <- 1

## creating variable for length in facility with NA (length_in_this_facility --> facility_length)
survey_no_NA$facility_length <- 0
survey_no_NA$facility_length[survey_no_NA$length_in_this_facility == "10 years or less"] <- -1
survey_no_NA$facility_length[survey_no_NA$length_in_this_facility == "Over 10 years"] <- 1
```


## Assault Weapons Ban

```{r}
## creating variables in the data frame with NA (stance_on_assault_weapons_ban --> assault_weapon_ban_stance)

## creating scale of political ideology, where 0 = undecided, -1 = conservative, and 1 = liberal

survey$assault_weapon_ban_stance <- 0
survey$assault_weapon_ban_stance[survey$stance_on_assault_weapons_ban == "Oppose"] <- -1
survey$assault_weapon_ban_stance[survey$stance_on_assault_weapons_ban == "Strongly oppose"] <- -1
survey$assault_weapon_ban_stance[survey$stance_on_assault_weapons_ban == "Support"] <- 1
survey$assault_weapon_ban_stance[survey$stance_on_assault_weapons_ban == "Strongly support"] <- 1

assault_weapon_ban_and_facility_length_table <- table(survey$assault_weapon_ban_stance, survey$length_in_this_facility)

knitr::kable(assault_weapon_ban_and_facility_length_table, digits = 4, caption = "Stance on Assault Weapons Ban Based on Jail Time")


assault_weapon_ban_and_facility_length_prop_table <- prop.table(table(survey$assault_weapon_ban_stance, survey$length_in_this_facility))

## creating variables the data frame with no NA (stance_on_assault_weapons_ban --> assault_weapon_ban_stance)

survey_no_NA$assault_weapon_ban_stance <- 0
survey_no_NA$assault_weapon_ban_stance[survey_no_NA$stance_on_assault_weapons_ban == "Oppose"] <- -1
survey_no_NA$assault_weapon_ban_stance[survey_no_NA$stance_on_assault_weapons_ban == "Strongly oppose"] <- -1
survey_no_NA$assault_weapon_ban_stance[survey_no_NA$stance_on_assault_weapons_ban == "Support"] <- 1
survey_no_NA$assault_weapon_ban_stance[survey_no_NA$stance_on_assault_weapons_ban == "Strongly support"] <- 1

assault_weapon_ban_and_facility_length_table_no_NA <- table(survey_no_NA$assault_weapon_ban_stance, survey_no_NA$length_in_this_facility)
knitr::kable(assault_weapon_ban_and_facility_length_table_no_NA, digits = 4, caption = "Stance on Assault Weapons Ban Based on Jail Time (no NA)")

assault_weapon_ban_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$assault_weapon_ban_stance, survey_no_NA$length_in_this_facility))

## random stuff
under_10_years <- subset(survey, length_in_this_facility == "10 years or less")
over_10_years <- subset(survey, length_in_this_facility == "Over 10 years")
```

## Marijuana Legalization

```{r}
## creating variables in the data frame with NA (stance_on_marijuana_legalization --> marijuana_legalization_stance)

## creating scale of political ideology, where 0 = undecided, -1 = conservative, and 1 = liberal

survey$marijuana_legalization_stance <- 0
survey$marijuana_legalization_stance[survey$stance_on_marijuana_legalization == "Oppose"] <- -1
survey$marijuana_legalization_stance[survey$stance_on_marijuana_legalization =="Strongly oppose"] <- -1
survey$marijuana_legalization_stance[survey$stance_on_marijuana_legalization == "Support"] <- 1
survey$marijuana_legalization_stance[survey$stance_on_marijuana_legalization == "Strongly support"] <- 1


marijiuana_legalization_and_facility_length_table <- table(survey$marijuana_legalization_stance, survey$length_in_this_facility)
knitr::kable(marijiuana_legalization_and_facility_length_table, digits = 4, caption = "Stance on Marijuana Legalization Based on Jail Time")

marijuana_legalization_and_facility_length_prop_table <- prop.table(table(survey$marijuana_legalization_stance, survey$length_in_this_facility))

## creating variables the data frame with no NA (stance_on_marijuana_legalization --> marijuana_legalization_stance)

survey_no_NA$marijuana_legalization_stance <- 0
survey_no_NA$marijuana_legalization_stance[survey_no_NA$stance_on_marijuana_legalization == "Oppose"] <- -1
survey_no_NA$marijuana_legalization_stance[survey_no_NA$stance_on_marijuana_legalization == "Strongly oppose"] <- -1
survey_no_NA$marijuana_legalization_stance[survey_no_NA$stance_on_marijuana_legalization == "Support"] <- 1
survey_no_NA$marijuana_legalization_stance[survey_no_NA$stance_on_marijuana_legalization == "Strongly support"] <- 1

marijiuana_legalization_and_facility_length_table_no_NA <- table(survey_no_NA$marijuana_legalization_stance, survey_no_NA$length_in_this_facility)
knitr::kable(marijiuana_legalization_and_facility_length_table_no_NA, digits = 4, caption = "Stance on Marijuana Legalization Based on Jail Time (no NA)")

marijiuana_legalization_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$marijuana_legalization_stance, survey_no_NA$length_in_this_facility))
```

## Border Security

```{r}
## creating variables in the data frame with NA (stance_on_tightening_border_security --> border_security_stance)

## creating scale of political ideology, where 0 = undecided, -1 = conservative, and 1 = liberal

survey$border_security_stance <- 0
survey$border_security_stance[survey$stance_on_tightening_border_security == "Oppose"] <- 1
survey$border_security_stance[survey$stance_on_tightening_border_security =="Strongly oppose"] <- 1
survey$border_security_stance[survey$stance_on_tightening_border_security == "Support"] <- -1
survey$border_security_stance[survey$stance_on_tightening_border_security == "Strongly support"] <- -1


border_security_and_facility_length_table <- table(survey$border_security_stance, survey$length_in_this_facility)
knitr::kable(border_security_and_facility_length_table, digits = 4, caption = "Stance on Border Security Based on Jail Time")

border_security_and_facility_length_prop_table <- prop.table(table(survey$border_security_stance, survey$length_in_this_facility))

## creating variables the data frame with no NA (stance_on_tightening_border_security --> border_security_stance)

survey_no_NA$border_security_stance <- 0
survey_no_NA$border_security_stance[survey_no_NA$stance_on_tightening_border_security == "Oppose"] <- 1
survey_no_NA$border_security_stance[survey_no_NA$stance_on_tightening_border_security == "Strongly oppose"] <- 1
survey_no_NA$border_security_stance[survey_no_NA$stance_on_tightening_border_security == "Support"] <- -1
survey_no_NA$border_security_stance[survey_no_NA$stance_on_tightening_border_security == "Strongly support"] <- -1

border_security_and_facility_length_table_no_NA <- table(survey_no_NA$border_security_stance, survey_no_NA$length_in_this_facility)
knitr::kable(border_security_and_facility_length_table_no_NA, digits = 4, caption = "Stance on Border Security Based on Jail Time (no NA)")

border_security_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$border_security_stance, survey_no_NA$length_in_this_facility))
```

## Minimum Wage

```{r}
## creating variables in the data frame with NA (stance_on_raise_min_wage --> minimum_wage_stance)

## creating scale of political ideology, where 0 = undecided, -1 = conservative, and 1 = liberal

survey$minimum_wage_stance <- 0
survey$minimum_wage_stance[survey$stance_on_raise_min_wage == "Oppose"] <- -1
survey$minimum_wage_stance[survey$stance_on_raise_min_wage == "Strongly oppose"] <- -1
survey$minimum_wage_stance[survey$stance_on_raise_min_wage == "Support"] <- 1
survey$minimum_wage_stance[survey$stance_on_raise_min_wage == "Strongly support"] <- 1


minimum_wage_and_facility_length_table <- table(survey$minimum_wage_stance, survey$length_in_this_facility)
knitr::kable(minimum_wage_and_facility_length_table, digits = 4, caption = "Stance on Raising Minumum Wage Based on Jail Time")

minimum_wage_and_facility_length_prop_table <- prop.table(table(survey$minimum_wage_stance, survey$length_in_this_facility))

## creating variables the data frame with no NA (stance_on_raise_min_wage --> minimum_wage_stance)

survey_no_NA$minimum_wage_stance <- 0
survey_no_NA$minimum_wage_stance[survey_no_NA$stance_on_raise_min_wage == "Oppose"] <- -1
survey_no_NA$minimum_wage_stance[survey_no_NA$stance_on_raise_min_wage == "Strongly oppose"] <- -1
survey_no_NA$minimum_wage_stance[survey_no_NA$stance_on_raise_min_wage == "Support"] <- 1
survey_no_NA$minimum_wage_stance[survey_no_NA$stance_on_raise_min_wage == "Strongly support"] <- 1

minimum_wage_and_facility_length_table_no_NA <- table(survey_no_NA$minimum_wage_stance, survey_no_NA$length_in_this_facility)
knitr::kable(minimum_wage_and_facility_length_table_no_NA, digits = 4, caption = "Stance on Raising Minumum Wage Based on Jail Time (no NA)")

minimum_wage_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$minimum_wage_stance, survey_no_NA$length_in_this_facility))
```


## Mean of Four Political Views (Arms Stance, Marijuana Legalization, Border Security, and Minimum Wage)

```{r}
## creating variable in the data frame with NA on mean of political attitudes
## the higher the mean, the more liberal the prisoner

survey$mean_four_political_views <- (survey$assault_weapon_ban_stance + survey$marijuana_legalization_stance + survey$border_security_stance + survey$minimum_wage_stance) / 4

mean_four_political_views_and_facility_length_table <- table(survey$mean_four_political_views, survey$length_in_this_facility)
knitr::kable(mean_four_political_views_and_facility_length_table, digits = 4, caption = "Average Political Stance Based on Jail Time")

mean_four_political_viewsand_facility_length_prop_table <- prop.table(table(survey$mean_four_political_views, survey$length_in_this_facility))

## creating variable in the data frame with no NA on mean of political attitudes

survey_no_NA$mean_four_political_views <- (survey_no_NA$assault_weapon_ban_stance + survey_no_NA$marijuana_legalization_stance + survey_no_NA$border_security_stance + survey_no_NA$minimum_wage_stance) / 4

mean_four_political_views_and_facility_length_table_no_NA <- table(survey_no_NA$mean_four_political_views, survey_no_NA$length_in_this_facility)
knitr::kable(mean_four_political_views_and_facility_length_table_no_NA, digits = 4, caption = "Average Political Stance Based on Jail Time (no NA)")

mean_four_political_viewsand_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$mean_four_political_views, survey_no_NA$length_in_this_facility))

## creating new political ideology variable with NA

survey$ideology[survey$mean_four_political_views == 1] <- "Very liberal"

survey$ideology[(survey$mean_four_political_views > 0) & (survey$mean_four_political_views < 1)] <- "Liberal"

survey$ideology[survey$mean_four_political_views == 0] <- "Politically neutral"

survey$ideology[(survey$mean_four_political_views < 0) & (survey$mean_four_political_views > -1)] <- "Conservative"

survey$ideology[survey$mean_four_political_views == -1] <- "Very conservative"

ideology_and_facility_length_table <- table(survey$ideology, survey$length_in_this_facility)
knitr::kable(ideology_and_facility_length_table, digits = 4, caption = "Average Political Ideology Based on Jail Time")

ideology_and_facility_length_prop_table <- prop.table(table(survey$ideology, survey$length_in_this_facility))

## creating new political ideology variable with no NA

survey_no_NA$ideology[survey_no_NA$mean_four_political_views == 1] <- "Very liberal"

survey_no_NA$ideology[(survey_no_NA$mean_four_political_views > 0) & (survey_no_NA$mean_four_political_views < 1)] <- "Liberal"

survey_no_NA$ideology[survey_no_NA$mean_four_political_views == 0] <- "Politically neutral"

survey_no_NA$ideology[(survey_no_NA$mean_four_political_views < 0) & (survey_no_NA$mean_four_political_views > -1)] <- "Conservative"

survey_no_NA$ideology[survey_no_NA$mean_four_political_views == -1] <- "Very conservative"

ideology_and_facility_length_table_no_NA <- table(survey_no_NA$ideology, survey_no_NA$length_in_this_facility)
knitr::kable(ideology_and_facility_length_table_no_NA, digits = 4, caption = "Average Political Ideology Based on Jail Time (no NA)")

ideology_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$ideology, survey_no_NA$length_in_this_facility))

```

## Regression

```{r}
## linear regression model comparing the mean of four political views and the length of time spent in prison with NA

mean_four_political_views_and_facility_length_fit <- lm(survey$mean_four_political_views ~ survey$length_in_this_facility)
mean_four_political_views_and_facility_length_fit

mean_four_political_views_and_facility_length_fit_plot <- plot(mean_four_political_views_and_facility_length_fit) 

mean_four_political_views_and_facility_length_fit_r_squared <- summary(mean_four_political_views_and_facility_length_fit)$r.squared
mean_four_political_views_and_facility_length_fit_r_squared

## linear regression model comparing the mean of four political views and the length of time spent in prison with no NA

mean_four_political_views_and_facility_length_fit_no_NA <- lm(survey_no_NA$mean_four_political_views ~ survey_no_NA$length_in_this_facility)
mean_four_political_views_and_facility_length_fit_no_NA

mean_four_political_views_and_facility_length_fit_no_NA_plot <- plot(mean_four_political_views_and_facility_length_fit_no_NA) 

mean_four_political_views_and_facility_length_fit__no_NA_r_squared <- summary(mean_four_political_views_and_facility_length_fit_no_NA)$r.squared
mean_four_political_views_and_facility_length_fit__no_NA_r_squared

```


## Random

```{r}
## FORMER PROBLEM SET NOTES
## gender_rep_table <- prop.table(table(judges$woman, judges$republican)) 
## rownames(gender_rep_table) <- c("Male", "Female") colnames(gender_rep_table) <- c("Democrat", "Republican")
## trains$age_group[trains$age >= 26 & trains$age <= 40] <- 2
## judges$any_girls[judges$girls >= 1] <- "1"
```

